/**
 * Setul larg de fraze (29.09.2026): 325 de mesaje scrise cum le scrie omul, pe grupuri,
 * cu suma și categoria așteptate, nu doar felul mesajului. S-a construit în trei runde:
 * primele două au ghidat reparațiile, a treia a fost scrisă după ele și măsurată nevăzută
 * (88% → 97%). Un caz nou care pică se marchează `pending` cu motiv, nu se ascunde.
 */
export type WideCase = { text: string; want: string | string[]; amount?: number; category?: string; pending?: boolean };

export const WIDE_CORPUS: WideCase[] = [
  {"text": "am dat 230 lei la Kaufland", "want": "expense", "amount": 230, "category": "Alimente"},
  {"text": "mega image 47,80", "want": "expense", "amount": 47.8, "category": "Alimente"},
  {"text": "profi 23 lei", "want": "expense", "amount": 23, "category": "Alimente"},
  {"text": "carrefour 312", "want": "expense", "amount": 312, "category": "Alimente"},
  {"text": "penny 64 lei", "want": "expense", "amount": 64, "category": "Alimente"},
  {"text": "am luat de la auchan de 180", "want": "expense", "amount": 180, "category": "Alimente"},
  {"text": "OMV 250 lei", "want": "expense", "amount": 250, "category": "Transport"},
  {"text": "petrom 300", "want": "expense", "amount": 300, "category": "Transport"},
  {"text": "am alimentat 220 lei", "want": "expense", "amount": 220, "category": "Transport"},
  {"text": "rovinieta 28 lei", "want": "expense", "amount": 28, "category": "Transport"},
  {"text": "parcare 10 lei", "want": "expense", "amount": 10, "category": "Transport"},
  {"text": "bilet de tren 76 lei", "want": "expense", "amount": 76, "category": "Transport"},
  {"text": "bolt 34 lei", "want": "expense", "amount": 34, "category": "Transport"},
  {"text": "uber 41", "want": "expense", "amount": 41, "category": "Transport"},
  {"text": "glovo 68 lei", "want": "expense", "amount": 68},
  {"text": "tazz 55", "want": "expense", "amount": 55},
  {"text": "emag 459 lei", "want": "expense", "amount": 459},
  {"text": "dedeman 120", "want": "expense", "amount": 120, "category": "Casă & facturi"},
  {"text": "am plătit factura la gaze 210", "want": "expense", "amount": 210, "category": "Casă & facturi"},
  {"text": "enel 187 lei", "want": "expense", "amount": 187, "category": "Casă & facturi"},
  {"text": "digi 60 lei", "want": "expense", "amount": 60},
  {"text": "internetul 50 lei", "want": "expense", "amount": 50},
  {"text": "apa canal 95", "want": "expense", "amount": 95, "category": "Casă & facturi"},
  {"text": "întreținerea 350", "want": "expense", "amount": 350, "category": "Casă & facturi"},
  {"text": "netflix 45", "want": "expense", "amount": 45, "category": "Abonamente"},
  {"text": "spotify 26 lei", "want": "expense", "amount": 26, "category": "Abonamente"},
  {"text": "abonament sala 150", "want": "expense", "amount": 150},
  {"text": "farmacia 67 lei", "want": "expense", "amount": 67, "category": "Sănătate"},
  {"text": "am dat 300 la dentist", "want": "expense", "amount": 300, "category": "Sănătate"},
  {"text": "analize 180 lei", "want": "expense", "amount": 180, "category": "Sănătate"},
  {"text": "pampers 89", "want": "expense", "amount": 89, "category": "Consumabile copil"},
  {"text": "scutece 75 lei", "want": "expense", "amount": 75, "category": "Consumabile copil"},
  {"text": "lapte praf 110", "want": "expense", "amount": 110, "category": "Consumabile copil"},
  {"text": "meditații 200 lei", "want": "expense", "amount": 200, "category": "Educație"},
  {"text": "rechizite 145", "want": "expense", "amount": 145, "category": "Educație"},
  {"text": "cinema 60 lei", "want": "expense", "amount": 60, "category": "Timp liber"},
  {"text": "restaurant 240", "want": "expense", "amount": 240},
  {"text": "bere 18 lei", "want": "expense", "amount": 18, "category": "Băuturi"},
  {"text": "o cafea 14", "want": "expense", "amount": 14},
  {"text": "ciocolată 9 lei", "want": "expense", "amount": 9, "category": "Dulciuri"},
  {"text": "apă plată 7 lei", "want": "expense", "amount": 7},
  {"text": "țigări 27", "want": "expense", "amount": 27},
  {"text": "am cumparat paine de 6 lei", "want": "expense", "amount": 6, "category": "Alimente"},
  {"text": "m-a costat 45 de lei tunsoarea", "want": "expense", "amount": 45},
  {"text": "s-au dus 90 de lei pe benzina", "want": "expense", "amount": 90, "category": "Transport"},
  {"text": "am scos 100 lei pe taxi", "want": "expense", "amount": 100, "category": "Transport"},
  {"text": "platit 40 parcare", "want": "expense", "amount": 40, "category": "Transport"},
  {"text": "azi la piata 85 lei", "want": "expense", "amount": 85, "category": "Alimente"},
  {"text": "i-am dat Anei 50 lei pentru cumparaturi", "want": "expense", "amount": 50},
  {"text": "am facut cumparaturi de 260", "want": "expense", "amount": 260, "category": "Alimente"},
  {"text": "cumpărături săptămânale 410 lei", "want": "expense", "amount": 410, "category": "Alimente"},
  {"text": "m-am dus la mall si am dat 350 pe haine", "want": "expense", "amount": 350},
  {"text": "am dat vreo 30 de lei pe covrigi", "want": "expense", "amount": 30, "category": "Alimente"},
  {"text": "cheltuiala 75 lei cadou", "want": "expense", "amount": 75},
  {"text": "pe mâncare 120", "want": "expense", "amount": 120, "category": "Alimente"},
  {"text": "am dat 20 la un cersetor", "want": "expense", "amount": 20},
  {"text": "taxa de școală 500", "want": "expense", "amount": 500, "category": "Educație"},
  {"text": "cincizeci de lei pe benzina", "want": "expense", "amount": 50, "category": "Transport"},
  {"text": "am dat o suta de lei la farmacie", "want": "expense", "amount": 100, "category": "Sănătate"},
  {"text": "douăzeci de lei taxi", "want": "expense", "amount": 20, "category": "Transport"},
  {"text": "am dat două sute pe alimente", "want": "expense", "amount": 200, "category": "Alimente"},
  {"text": "o mie de lei pe telefon", "want": "expense", "amount": 1000},
  {"text": "1,5k pe laptop", "want": "expense", "amount": 1500},
  {"text": "2 mii pe frigider", "want": "expense", "amount": 2000},
  {"text": "am dat 1 200 lei pe canapea", "want": "expense", "amount": 1200},
  {"text": "benzina 250ron", "want": "expense", "amount": 250, "category": "Transport"},
  {"text": "taxi 30lei", "want": "expense", "amount": 30, "category": "Transport"},
  {"text": "RON 45 farmacie", "want": "expense", "amount": 45, "category": "Sănătate"},
  {"text": "am dat 12.5 lei pe apa", "want": "expense", "amount": 12.5},
  {"text": "am dta 50 pe benzina", "want": "expense", "amount": 50, "category": "Transport"},
  {"text": "am chletuit 70 pe mancare", "want": "expense", "amount": 70, "category": "Alimente"},
  {"text": "benzna 200", "want": "expense", "amount": 200, "category": "Transport"},
  {"text": "farmaice 40", "want": "expense", "amount": 40, "category": "Sănătate"},
  {"text": "AM DAT 60 LEI PE TAXI", "want": "expense", "amount": 60, "category": "Transport"},
  {"text": "kaufland  150   lei", "want": "expense", "amount": 150, "category": "Alimente"},
  {"text": "am platit 35 lei la farmacie ieri", "want": "expense", "amount": 35, "category": "Sănătate"},
  {"text": "am dat 50 cash la piata", "want": "expense", "amount": 50, "category": "Alimente"},
  {"text": "pe tichete 120 la lidl", "want": "expense", "amount": 120, "category": "Alimente"},
  {"text": "cu cardul 80 benzina", "want": "expense", "amount": 80, "category": "Transport"},
  {"text": "Ana a dat 60 pe haine", "want": "expense", "amount": 60},
  {"text": "mi-a venit pensia 2300", "want": "income", "amount": 2300},
  {"text": "alocatia copilului 719", "want": "income", "amount": 719},
  {"text": "am primit chiria de la chiriaș 1500", "want": "income", "amount": 1500},
  {"text": "am vandut bicicleta pe olx cu 400", "want": "income", "amount": 400},
  {"text": "am încasat 800 de la un client", "want": "income", "amount": 800},
  {"text": "freelance 1200 lei", "want": "income", "amount": 1200},
  {"text": "am câștigat 300 la pariuri", "want": "income", "amount": 300},
  {"text": "cashback 25 lei", "want": "income", "amount": 25},
  {"text": "mi-au dat ai mei 500", "want": "income", "amount": 500},
  {"text": "am primit ajutorul de somaj 900", "want": "income", "amount": 900},
  {"text": "prima de craciun 1000", "want": "income", "amount": 1000},
  {"text": "salariu 5.200", "want": "income", "amount": 5200},
  {"text": "a intrat leafa 4800", "want": "income", "amount": 4800},
  {"text": "Ana a luat salariul 3900", "want": "income", "amount": 3900},
  {"text": "mi-a dat șeful un bonus de 600", "want": "income", "amount": 600},
  {"text": "am primit înapoi 200 de la Mihai", "want": "income", "amount": 200},
  {"text": "dividende 350", "want": "income", "amount": 350},
  {"text": "am primit tichetele 400", "want": "income", "amount": 400},
  {"text": "fa un plic de 600 pentru mancare", "want": "envelope", "amount": 600},
  {"text": "plic nou benzina 400", "want": "envelope", "amount": 400},
  {"text": "vreau plic pentru copii 300", "want": "envelope", "amount": 300},
  {"text": "seteaza bugetul de alimente la 1800", "want": "envelope", "amount": 1800},
  {"text": "pune 200 deoparte pentru vacanta", "want": "envelope"},
  {"text": "creeaza plicul Haine cu 250", "want": "envelope", "amount": 250},
  {"text": "aloca 500 lei pentru facturi", "want": "envelope", "amount": 500},
  {"text": "buget distractie 300 pe luna", "want": "envelope", "amount": 300},
  {"text": "mareste transportul la 700", "want": "envelope"},
  {"text": "mai adauga 100 la plicul copii", "want": "envelope"},
  {"text": "sterge plicul copii", "want": "envelope-delete"},
  {"text": "nu mai am nevoie de plicul de transport", "want": "envelope-delete"},
  {"text": "am un credit de nevoi personale 25000, rata 900", "want": "debt", "amount": 25000},
  {"text": "îi datorez lui Mihai 500 de lei", "want": "debt", "amount": 500},
  {"text": "card de credit 3000 datorie", "want": "debt", "amount": 3000},
  {"text": "leasing masina 450 pe luna pe 20", "want": "recurring", "amount": 450},
  {"text": "abonament internet 50 lei in fiecare luna pe 10", "want": "recurring", "amount": 50},
  {"text": "in fiecare luna pe 15 platesc gradinita 800", "want": "recurring", "amount": 800},
  {"text": "vreau sa strang 5000 pana in vara", "want": "goal", "amount": 5000},
  {"text": "economisesc pentru masina 20000", "want": "goal", "amount": 20000},
  {"text": "ziua mamei pe 12 noiembrie, 300 lei cadou", "want": "planned-event", "amount": 300},
  {"text": "botez in decembrie cam 1000", "want": "planned-event", "amount": 1000},
  {"text": "salariul imi intra pe 10 in fiecare luna", "want": "payday"},
  {"text": "urmatoarea leafa e pe 9 octombrie", "want": "payday"},
  {"text": "am 2000 lei in cont", "want": "funds", "amount": 2000},
  {"text": "am 350 cash in portofel", "want": "funds", "amount": 350},
  {"text": "cat am dat pe benzina luna asta", "want": "answer"},
  {"text": "cat mai am la alimente", "want": "answer"},
  {"text": "cat pot sa cheltui azi", "want": "answer"},
  {"text": "cat am cheltuit in total", "want": "answer"},
  {"text": "pe ce dau cei mai multi bani", "want": "answer"},
  {"text": "am depasit bugetul?", "want": "answer"},
  {"text": "imi ajung banii pana la salariu", "want": "answer"},
  {"text": "cat am la transport", "want": "answer"},
  {"text": "cate zile mai sunt pana la salariu", "want": "answer"},
  {"text": "ce facturi am de platit", "want": "answer"},
  {"text": "cand platesc chiria", "want": "answer"},
  {"text": "cat am economisit", "want": "answer"},
  {"text": "cat a cheltuit Ana", "want": "answer"},
  {"text": "care e soldul pe card", "want": "answer"},
  {"text": "ce plicuri am", "want": "answer"},
  {"text": "cat mi-a ramas", "want": "answer"},
  {"text": "cat am dat la kaufland", "want": "answer"},
  {"text": "merg bine luna asta?", "want": "answer"},
  {"text": "unde pot sa tai din cheltuieli", "want": "answer"},
  {"text": "cat e media pe zi", "want": "answer"},
  {"text": "muta 150 de la transport la alimente", "want": "transfer", "amount": 150},
  {"text": "ia 100 din copii si pune la alimente", "want": "transfer", "amount": 100},
  {"text": "sterge cheltuiala de la lidl", "want": "revise"},
  {"text": "am gresit suma, era 45", "want": "revise"},
  {"text": "modifica ultima cheltuiala in 80", "want": "revise"},
  {"text": "am achitat chiria", "want": "due"},
  {"text": "chiria e platita", "want": "due"},
  {"text": "da, salveaza", "want": "confirm"},
  {"text": "e bine asa", "want": "confirm"},
  {"text": "perfect", "want": "confirm"},
  {"text": "salut", "want": ["none", "answer"]},
  {"text": "ce faci?", "want": ["none", "answer"]},
  {"text": "multumesc mult", "want": ["none", "answer"]},
  {"text": "esti tare", "want": ["none", "answer"]},
  {"text": "ce vreme e maine", "want": ["none", "answer"]},
  {"text": "spune-mi o gluma", "want": ["none", "answer"]},
  {"text": "am dat 50 pe benzina si 30 pe parcare", "want": "expense", "amount": 50},
  {"text": "salariu 5000, pune 1600 la alimente si 500 la transport", "want": ["income", "envelope"]},
  {"text": "am dat 75 lei la benzinărie", "want": "expense", "amount": 75, "category": "Transport"},
  {"text": "lukoil 180", "want": "expense", "amount": 180, "category": "Transport"},
  {"text": "spălătorie auto 40", "want": "expense", "amount": 40, "category": "Transport"},
  {"text": "am luat bilet la autobuz 5 lei", "want": "expense", "amount": 5, "category": "Transport"},
  {"text": "taxiul m-a costat 37", "want": "expense", "amount": 37, "category": "Transport"},
  {"text": "revizie la masina 900", "want": "expense", "amount": 900},
  {"text": "lidl 96,40", "want": "expense", "amount": 96.4, "category": "Alimente"},
  {"text": "am cumpărat carne de 85 lei", "want": "expense", "amount": 85, "category": "Alimente"},
  {"text": "fructe si legume 60", "want": "expense", "amount": 60, "category": "Alimente"},
  {"text": "brutărie 14 lei", "want": "expense", "amount": 14, "category": "Alimente"},
  {"text": "am comandat pizza 70", "want": "expense", "amount": 70},
  {"text": "mâncare la birou 32", "want": "expense", "amount": 32, "category": "Alimente"},
  {"text": "factura la telefon 55", "want": "expense", "amount": 55},
  {"text": "curentul 230 lei", "want": "expense", "amount": 230, "category": "Casă & facturi"},
  {"text": "gazele 180", "want": "expense", "amount": 180, "category": "Casă & facturi"},
  {"text": "am plătit întreținerea 420", "want": "expense", "amount": 420, "category": "Casă & facturi"},
  {"text": "abonamentul la sală 120", "want": "expense", "amount": 120},
  {"text": "youtube premium 30", "want": "expense", "amount": 30, "category": "Abonamente"},
  {"text": "am dat 45 lei pe pastile", "want": "expense", "amount": 45, "category": "Sănătate"},
  {"text": "consultație la medic 250", "want": "expense", "amount": 250, "category": "Sănătate"},
  {"text": "ochelari 600", "want": "expense", "amount": 600, "category": "Sănătate"},
  {"text": "scutece si servetele 110", "want": "expense", "amount": 110, "category": "Consumabile copil"},
  {"text": "pepco 90 lei", "want": "expense", "amount": 90, "category": "Consumabile copil"},
  {"text": "excursie cu școala 150", "want": "expense", "amount": 150, "category": "Educație"},
  {"text": "bilete la teatru 180", "want": "expense", "amount": 180, "category": "Timp liber"},
  {"text": "am ieșit în oraș 150", "want": "expense", "amount": 150},
  {"text": "cadou pentru nași 300", "want": "expense", "amount": 300},
  {"text": "două sute cincizeci pe rechizite", "want": "expense", "amount": 250, "category": "Educație"},
  {"text": "am dat trei sute pe haine", "want": "expense", "amount": 300},
  {"text": "cam 40 de lei pe cafele", "want": "expense", "amount": 40},
  {"text": "o sută cincizeci la farmacie", "want": "expense", "amount": 150, "category": "Sănătate"},
  {"text": "zece lei parcarea", "want": "expense", "amount": 10, "category": "Transport"},
  {"text": "3k pe vacanță", "want": "expense", "amount": 3000},
  {"text": "am platiit 60 benzina", "want": "expense", "amount": 60, "category": "Transport"},
  {"text": "farmacie 3o lei", "want": "expense"},
  {"text": "kaufladn 120", "want": "expense", "amount": 120, "category": "Alimente"},
  {"text": "am dat cash 30 pe paine", "want": "expense", "amount": 30, "category": "Alimente"},
  {"text": "ieri seara 55 lei la restaurant", "want": "expense", "amount": 55},
  {"text": "săptămâna trecută am dat 200 la dedeman", "want": "expense", "amount": 200, "category": "Casă & facturi"},
  {"text": "am luat salariul 4700", "want": "income", "amount": 4700},
  {"text": "mi-a venit alocația 719", "want": "income", "amount": 719},
  {"text": "pensia mamei 1900", "want": "income", "amount": 1900},
  {"text": "am încasat chiria 1600", "want": "income", "amount": 1600},
  {"text": "am vândut telefonul vechi cu 500", "want": "income", "amount": 500},
  {"text": "un client mi-a plătit 900", "want": "income", "amount": 900},
  {"text": "am primit bani de ziua mea 300", "want": "income", "amount": 300},
  {"text": "bursa 600 lei", "want": "income", "amount": 600},
  {"text": "mi s-a returnat 120 de la emag", "want": "income", "amount": 120},
  {"text": "a intrat al 13-lea salariu 4000", "want": "income", "amount": 4000},
  {"text": "fă-mi un plic de haine cu 300", "want": "envelope", "amount": 300},
  {"text": "vreau 400 pe luna pentru benzina", "want": "envelope", "amount": 400},
  {"text": "setează limita la transport 600", "want": "envelope", "amount": 600},
  {"text": "mai pune 150 în plicul de alimente", "want": "envelope"},
  {"text": "scoate plicul de haine", "want": "envelope-delete"},
  {"text": "plic pentru vacanță 2000", "want": "envelope", "amount": 2000},
  {"text": "mută 200 din alimente în copii", "want": "transfer", "amount": 200},
  {"text": "trece 50 de la copii la transport", "want": "transfer", "amount": 50},
  {"text": "am un împrumut la bancă de 15000 cu rata 700", "want": "debt", "amount": 15000},
  {"text": "îi dau înapoi fratelui 300 luna viitoare", "want": "debt", "amount": 300},
  {"text": "abonament netflix 45 pe 8 ale lunii", "want": "recurring", "amount": 45},
  {"text": "rata la frigider 250 pe 20", "want": "recurring", "amount": 250},
  {"text": "vreau să adun 3000 pentru o mașină de spălat", "want": "goal", "amount": 3000},
  {"text": "strâng bani de un laptop, cam 4000", "want": "goal", "amount": 4000},
  {"text": "nunta vărului în iunie, 1000 de lei", "want": "planned-event", "amount": 1000},
  {"text": "ziua lui Andrei pe 5 decembrie 200 lei", "want": "planned-event", "amount": 200},
  {"text": "salariul vine pe 12", "want": "payday"},
  {"text": "iau leafa pe 25 în fiecare lună", "want": "payday"},
  {"text": "am 1200 pe card", "want": "funds", "amount": 1200},
  {"text": "am 80 de lei cash", "want": "funds", "amount": 80},
  {"text": "cât am cheltuit azi", "want": "answer"},
  {"text": "ce cheltuieli am avut ieri", "want": "answer"},
  {"text": "cât am dat pe mâncare săptămâna asta", "want": "answer"},
  {"text": "mai am bani la transport?", "want": "answer"},
  {"text": "cât îmi rămâne până la salariu", "want": "answer"},
  {"text": "cum stau luna asta", "want": "answer"},
  {"text": "sunt pe plus sau pe minus", "want": "answer"},
  {"text": "ce abonamente plătesc", "want": "answer"},
  {"text": "cât datorez în total", "want": "answer"},
  {"text": "cât am pus deoparte", "want": "answer"},
  {"text": "când intră salariul", "want": "answer"},
  {"text": "pe ce am cheltuit cel mai mult", "want": "answer"},
  {"text": "cât a dat Ana săptămâna asta", "want": "answer"},
  {"text": "am cheltuit mai mult decât luna trecută?", "want": "answer"},
  {"text": "cât pot da azi pe mâncare", "want": "answer"},
  {"text": "șterge ultima", "want": "revise"},
  {"text": "am scris greșit, erau 35", "want": "revise"},
  {"text": "corectează ultima cheltuială la 60", "want": "revise"},
  {"text": "am plătit și chiria", "want": "due"},
  {"text": "gata cu chiria luna asta, am dat-o", "want": "due"},
  {"text": "da", "want": "confirm"},
  {"text": "ok, salvează", "want": "confirm"},
  {"text": "da, e corect", "want": "confirm"},
  {"text": "exact asa", "want": "confirm"},
  {"text": "bun", "want": "confirm"},
  {"text": "bună seara", "want": ["none", "answer"]},
  {"text": "mulțumesc frumos", "want": ["none", "answer"]},
  {"text": "ce poți să faci?", "want": ["none", "answer"]},
  {"text": "ajutor", "want": ["none", "answer"]},
  {"text": "am băgat benzină de 150", "want": "expense", "amount": 150, "category": "Transport"},
  {"text": "mol 210", "want": "expense", "amount": 210, "category": "Transport"},
  {"text": "abonament stb 80", "want": "expense", "amount": 80},
  {"text": "am dat 25 pe un taxi aseară", "want": "expense", "amount": 25, "category": "Transport"},
  {"text": "cumpărături la selgros 540", "want": "expense", "amount": 540, "category": "Alimente"},
  {"text": "am luat de mâncare 45", "want": "expense", "amount": 45, "category": "Alimente"},
  {"text": "pâine lapte ouă 32 lei", "want": "expense", "amount": 32, "category": "Alimente"},
  {"text": "covrigi 6", "want": "expense", "amount": 6, "category": "Alimente"},
  {"text": "am plătit netul 60", "want": "expense", "amount": 60},
  {"text": "factura enel 199,99", "want": "expense", "amount": 199.99, "category": "Casă & facturi"},
  {"text": "orange 49", "want": "expense", "amount": 49},
  {"text": "hbo max 25 lei", "want": "expense", "amount": 25, "category": "Abonamente"},
  {"text": "sensiblu 58", "want": "expense", "amount": 58, "category": "Sănătate"},
  {"text": "am dat 120 pe un control la dentist", "want": "expense", "amount": 120, "category": "Sănătate"},
  {"text": "vitamine pentru copii 70", "want": "expense", "amount": 70, "category": "Sănătate"},
  {"text": "am luat jucării de 90", "want": "expense", "amount": 90},
  {"text": "grădinița 650", "want": "expense", "amount": 650, "category": "Educație"},
  {"text": "carte de școală 45", "want": "expense", "amount": 45, "category": "Educație"},
  {"text": "concert 200 lei", "want": "expense", "amount": 200, "category": "Timp liber"},
  {"text": "am dat 70 la bowling", "want": "expense", "amount": 70},
  {"text": "haine de la zara 340", "want": "expense", "amount": 340},
  {"text": "am plătit 15 la spălătorie", "want": "expense", "amount": 15},
  {"text": "patru sute pe o bicicletă", "want": "expense", "amount": 400},
  {"text": "am dat cinci sute pe reparații", "want": "expense", "amount": 500},
  {"text": "doi lei pe o sticlă de apă", "want": "expense", "amount": 2},
  {"text": "mie cinci sute pe mobilă", "want": "expense"},
  {"text": "am dta 20 pe pâine", "want": "expense", "amount": 20, "category": "Alimente"},
  {"text": "bnzina 300", "want": "expense", "amount": 300, "category": "Transport"},
  {"text": "farmacei 25", "want": "expense", "amount": 25, "category": "Sănătate"},
  {"text": "am încasat salariul pe septembrie 5100", "want": "income", "amount": 5100},
  {"text": "pensia a intrat 2100", "want": "income", "amount": 2100},
  {"text": "mi-a dat bunica 200", "want": "income", "amount": 200},
  {"text": "am primit o primă de 800", "want": "income", "amount": 800},
  {"text": "am vândut ceva pe olx 150", "want": "income", "amount": 150},
  {"text": "câștig la loto 50", "want": "income", "amount": 50},
  {"text": "mi s-a virat alocația 719", "want": "income", "amount": 719},
  {"text": "vreau un plic de 250 pentru cadouri", "want": "envelope", "amount": 250},
  {"text": "pune 1000 pe luna la economii", "want": "envelope", "amount": 1000, "pending": true},
  {"text": "elimina plicul cadouri", "want": "envelope-delete"},
  {"text": "mută 80 din distracție în alimente", "want": "transfer"},
  {"text": "am un credit ipotecar, mai am 180000 de plătit", "want": "debt", "amount": 180000},
  {"text": "rata la bancă 1200 pe 1", "want": "recurring", "amount": 1200},
  {"text": "vreau să strâng 2000 pentru vacanță până în iulie", "want": "goal", "amount": 2000},
  {"text": "ziua copilului pe 20 ianuarie, 500", "want": "planned-event", "amount": 500},
  {"text": "salariul intră pe 15", "want": "payday"},
  {"text": "am 500 lei în cont", "want": "funds", "amount": 500},
  {"text": "cât am cheltuit pe benzină", "want": "answer"},
  {"text": "cât mai am în plicul de transport", "want": "answer"},
  {"text": "câți bani mai am", "want": "answer"},
  {"text": "ce am plătit azi", "want": "answer"},
  {"text": "mai pot cheltui ceva azi?", "want": "answer"},
  {"text": "cât m-a costat mâncarea luna asta", "want": "answer"},
  {"text": "ce datorii am", "want": "answer"},
  {"text": "cine a cheltuit cel mai mult", "want": "answer"},
  {"text": "ajung banii până pe 9?", "want": "answer"},
  {"text": "care sunt cheltuielile fixe", "want": "answer"},
  {"text": "anulează ultima cheltuială", "want": "revise"},
  {"text": "am greșit, era 25", "want": "revise"},
  {"text": "chiria am plătit-o", "want": "due"},
  {"text": "da te rog", "want": "confirm"},
  {"text": "sigur, adaugă", "want": "confirm"},
  {"text": "corect", "want": "confirm"},
  {"text": "okey", "want": "confirm"},
  {"text": "ce mai faci", "want": ["none", "answer"]},
  {"text": "hello", "want": ["none", "answer"]},
];
