import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import "./atelier-refinement.css";
import "./upgrade.css";
import "./risk-state.css";
import "./reports.css";
import "./recurring.css";
import "./atelier-stationery.css";
import "./assistant-checkin.css";
import "./receipt-mobile.css";
import "./family-guide.css";
import "./workbench-final.css";
import "./dark-mobile-repair.css";
import "./advisor-studio.css";
import "./advisor-dark-fix.css";
import "./atelier-review-pass.css";
import "./personal-dashboard.css";
import "./smart-scenario.css";
import "./atelier-semantic-pass.css";
import "./bf-logo-3d.css";
import "./atelier-review-final.css";
import "./dark-night-premium.css";
import "./envelope-source.css";
import "./envelope-transfer.css";
import "./envelope-insights.css";
import "./mobile-decision-fix.css";
import "./themes.css";
import "./report-balance.css";
import "./objective-edit.css";
import "./balance-scope.css";
import "./transaction-envelope-picker.css";
import "./advisor-personalized.css";
import "./professional-type-navigation.css";
import "./workbench-surface-system.css";
import "./redesign-major-mobile.css";
import "./plan-studio.css";
import "./analysis-studio.css";
import "./clarity-rebuild.css";
import "./ledger-decision-pass.css";
import "./ledger-movements-pass.css";
import "./priority-focus-pass.css";
import "./envelope-weekly-toggle.css";
import "./secondary-button-contrast.css";
import "./week-transfer.css";
import "./expanded-themes.css";
import "./plan-header-stat.css";
import "./theme-picker-scroll.css";
import "./modernization-pass.css";
import "./health-score.css";
import "./theme-contrast-pass.css";
import "./play-studio.css";

createRoot(document.getElementById("root")!).render(<App />);

if (import.meta.env.PROD && "serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    void navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(() => undefined);
  });
}
