import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import "./atelier-refinement.css";
import "./upgrade.css";
import "./risk-state.css";
import "./reports.css";
import "./recurring.css";
import "./atelier-stationery.css";
import "./assistant-checkin.css";
import "./receipt-mobile.css";
import "./family-guide.css";
import "./workbench-final.css";
import "./dark-mobile-repair.css";
import "./advisor-studio.css";
import "./advisor-dark-fix.css";
import "./atelier-review-pass.css";
import "./personal-dashboard.css";
import "./smart-scenario.css";
import "./atelier-semantic-pass.css";
import "./bf-logo-3d.css";
import "./atelier-review-final.css";
import "./dark-night-premium.css";
import "./envelope-source.css";
import "./envelope-transfer.css";
import "./envelope-insights.css";
import "./mobile-decision-fix.css";
import "./themes.css";
import "./report-balance.css";
import "./objective-edit.css";
import "./transaction-envelope-picker.css";
import "./advisor-personalized.css";
import "./professional-type-navigation.css";
import "./workbench-surface-system.css";

createRoot(document.getElementById("root")!).render(<App />);
