/** Formularele de datorie și economisire. Scos din home-secondary. */
import { useState } from "react";
import { Check } from "lucide-react";
import { isoToday, newId, parseRomanianAmount, recordDebtPayment, sourceBalance, type AppData, type Debt, type SavingsGoal } from "@/lib/finance-data";
import { Field, Modal, dateText, money } from "@/pages/home-kit";
import { t } from "@/lib/i18n";
import { RoDateInput } from "@/components/RoDateInput";
import { askConfirm } from "@/lib/confirm-dialog";

export function GoalForm({ data, type, item, onSave, onClose }: { data: AppData; type: "debt" | "saving"; item?: Debt | SavingsGoal; onSave: (item: Debt | SavingsGoal) => void; onClose: () => void }) {
  const saving = type === "saving"; const old = item as SavingsGoal | undefined; const oldDebt = item as Debt | undefined;
  const [name, setName] = useState(item?.name || ""); const [one, setOne] = useState(item ? String(saving ? old?.current ?? 0 : oldDebt?.remaining ?? 0) : ""); const [two, setTwo] = useState(item ? String(saving ? old?.target ?? 0 : oldDebt?.monthly ?? 0) : ""); const [date, setDate] = useState(item?.dueDate || ""); const [memberId, setMemberId] = useState(item?.memberId || ""); const [error, setError] = useState("");
  const [rate, setRate] = useState(oldDebt?.annualRate ? String(oldDebt.annualRate).replace(".", ",") : ""); const [kind, setKind] = useState<Debt["kind"] | "">(oldDebt?.kind || ""); const [endDate, setEndDate] = useState(oldDebt?.endDate || "");
  /** `updatedAt` decide ce versiune câștigă la unirea a două telefoane; fără el modificarea mai nouă putea fi ignorată. */
  const save = () => { const first = parseRomanianAmount(one); const second = parseRomanianAmount(two); if (!name.trim() || first < 0 || second < 0 || (saving && second <= 0)) return setError(t("Completează numele și sumele corecte.")); const now = new Date().toISOString(); if (saving) onSave({ id: item?.id || newId("goal"), name: name.trim(), current: first, target: second, due: date ? dateText(date, true) : t("Fără termen"), dueDate: date || undefined, memberId: memberId || undefined, tone: old?.tone || "honey", updatedAt: now }); else onSave({ id: item?.id || newId("debt"), name: name.trim(), remaining: first, monthly: second, due: date ? dateText(date, true) : t("Nespecificat"), dueDate: date || undefined, memberId: memberId || undefined, tone: oldDebt?.tone || "coral", annualRate: parseRomanianAmount(rate) > 0 ? parseRomanianAmount(rate) : undefined, kind: kind || undefined, endDate: endDate || undefined, updatedAt: now }); onClose(); };
  return <Modal title={saving ? t("Obiectiv de economisire") : t("Datorie sau rată")} onClose={onClose}><div className="bf-form-grid"><Field label={saving ? t("Pentru ce economisiți?") : t("Denumire")}><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={saving ? t("ex. Fond de siguranță") : t("ex. Credit bancar")} /></Field><Field label={t("Aparține de")}><select value={memberId} onChange={(event) => setMemberId(event.target.value)}><option value="">{t("Familie / comun")}</option>{data.settings.members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></Field><Field label={saving ? t("Strâns până acum (lei)") : t("Sold rămas (lei)")}><input value={one} onChange={(event) => setOne(event.target.value)} inputMode="decimal" /></Field><Field label={saving ? t("Țintă (lei)") : t("Rată lunară (lei)")}><input value={two} onChange={(event) => setTwo(event.target.value)} inputMode="decimal" /></Field><Field label={saving ? t("Data țintă") : t("Scadență")}><RoDateInput value={date} onChange={(event) => setDate(event.target.value)} /></Field>{!saving && <><Field label={t("Tip")}><select value={kind} onChange={(event) => setKind(event.target.value as Debt["kind"] | "")}><option value="">{t("Nespecificat")}</option><option value="credit">{t("Credit bancar")}</option><option value="card">{t("Card de credit")}</option><option value="ifn">{t("IFN")}</option><option value="persoane">{t("De la persoane")}</option></select></Field><Field label={t("Dobândă anuală (%)")}><input value={rate} onChange={(event) => setRate(event.target.value)} inputMode="decimal" placeholder={t("ex. 18,5")} /></Field><Field label={t("Ultima rată (opțional)")}><RoDateInput value={endDate} onChange={(event) => setEndDate(event.target.value)} /></Field></>}</div>{!saving && <p className="bf-helper">{t("Dobânda o găsești în contract (DAE sau dobânda anuală). Cu ea calculăm câte rate mai sunt, cât plătești în total și ce datorie merită închisă întâi.")}</p>}{error && <p className="bf-form-error" role="alert">{error}</p>}<button className="bf-primary full" onClick={save}><Check size={17} /> {t("Salvează")}</button></Modal>;
}

export function DebtPaymentForm({ data, debt, onSave, onClose }: { data: AppData; debt: Debt; /** Funcțional: plata se aplică pe registrul de după confirmare, nu pe copia de la apăsare. */ onSave: (update: (current: AppData) => AppData) => void; onClose: () => void }) {
  const defaultMemberId = debt.memberId || data.settings.members[0]?.id || ""; const [amount, setAmount] = useState(String(Math.min(debt.monthly || debt.remaining, debt.remaining))); const [date, setDate] = useState(isoToday()); const [memberId, setMemberId] = useState(defaultMemberId); const paymentSources = data.settings.paymentSources.filter((source) => !source.memberId || source.memberId === memberId); const [sourceId, setSourceId] = useState(data.settings.paymentSources.find((source) => source.memberId === defaultMemberId)?.id || data.settings.paymentSources.find((source) => !source.memberId)?.id || data.settings.paymentSources[0]?.id || ""); const [note, setNote] = useState(""); const [error, setError] = useState("");
  const pay = async () => { const value = parseRomanianAmount(amount); if (value <= 0) return setError(t("Introdu o sumă mai mare decât zero.")); if (value > debt.remaining) return setError(t("Poți plăti cel mult {amount} pentru această datorie.", { amount: money(debt.remaining) })); const next = recordDebtPayment(data, { debtId: debt.id, amount: value, sourceId, memberId, date, note }); if (!next) return setError(t("Alege un membru și o sursă de plată valide.")); if (!await askConfirm(t("Confirmi plata de {amount} pentru „{name}”? Soldul datoriei va deveni {remaining}.", { amount: money(value), name: debt.name, remaining: money(debt.remaining - value) }))) return; onSave((current) => recordDebtPayment(current, { debtId: debt.id, amount: value, sourceId, memberId, date, note }) ?? current); onClose(); };
  const ownerName = (sourceId: string) => data.settings.members.find((member) => member.id === data.settings.paymentSources.find((source) => source.id === sourceId)?.memberId)?.name || t("Comun");
  return <Modal title={t("Plătește rata · {name}", { name: debt.name })} onClose={onClose}><section className="bf-debt-payment-intro"><p className="bf-kicker">{t("MIȘCARE REALĂ + DATORIE")}</p><p>{t("Plata este adăugată în Jurnal și scade aceeași sumă din soldul rămas. Nu pornește plăți bancare automate.")}</p><strong>{t("{amount} rămași", { amount: money(debt.remaining) })}</strong></section><div className="bf-form-grid"><Field label={t("Sumă plătită (lei)")}><input autoFocus value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" /></Field><Field label={t("Data plății")}><RoDateInput value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label={t("Membru")}><select value={memberId} onChange={(event) => { const nextMember = event.target.value; setMemberId(nextMember); const firstSource = data.settings.paymentSources.find((source) => !source.memberId || source.memberId === nextMember); if (firstSource) setSourceId(firstSource.id); }}>{data.settings.members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></Field><Field label={t("Plătit din")}><select value={sourceId} onChange={(event) => setSourceId(event.target.value)}>{paymentSources.map((source) => <option key={source.id} value={source.id}>{source.name} · {ownerName(source.id)} · {money(sourceBalance(data, source.id))}</option>)}</select></Field></div><Field label={t("Notiță opțională")}><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder={t("ex. rata august, plată parțială")} /></Field>{error && <p className="bf-form-error" role="alert">{error}</p>}<button className="bf-primary full" onClick={pay}><Check size={17} /> {t("Confirmă plata ratei")}</button></Modal>;
}
