import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, BellRing, CalendarClock, ChevronRight, Goal, LayoutDashboard, Plus, ReceiptText, WalletCards, X } from "lucide-react";
import { allocationStatus, financialBalance, formatDate, isoToday, planForecast, type AppData } from "@/lib/finance-data";
import { calendarBudgetWeekKey, currentCalendarBudgetWeek } from "@/lib/calendar-budget";
import { WeeklySummaryPanel } from "@/components/WeeklySummaryPanel";
import { HealthScoreBadge } from "@/components/HealthScoreBadge";
import { AllocationHistoryChart } from "@/components/AllocationHistoryChart";
import { allocationHistorySnapshot } from "@/lib/allocation-history";
import { advisorSignals, dateText, fmtExact, money, planMath, type AdvisorAction, type MainView } from "./home-shared";

export function TodayView({ data, onAdd, onGo }: { data: AppData; onAdd: () => void; onGo: (view: MainView) => void }) {
  const math = planMath(data); const forecast = planForecast(data); const signals = advisorSignals(data); const balance = financialBalance(data, math.plan.periodStart, math.planEnd); const [dismissedAlerts, setDismissedAlerts] = useState<string[]>([]); const [shownTrancheKey, setShownTrancheKey] = useState("");
  const envelopes = data.settings.salaryPlan.allocations.map((item) => ({ item, ...allocationStatus(data, item) })); const topEnvelope = [...envelopes].sort((a, b) => b.usage - a.usage)[0]; const activeEnvelopeAlert = envelopes.filter((item) => item.state !== "healthy" && !dismissedAlerts.includes(item.item.id)).sort((a, b) => (b.state === "over" ? 2 : 1) - (a.state === "over" ? 2 : 1))[0]; const lastMoves = data.transactions.slice(0, 3); const overPlan = math.remaining < 0; const daily = math.plan.nextPayday ? forecast.safeDaily : 0;
  const activeTranche = math.planEnd ? currentCalendarBudgetWeek(math.weeklyPacedTotal, math.plan.periodStart, math.planEnd, isoToday()) : undefined; const activeTrancheKey = activeTranche ? calendarBudgetWeekKey(activeTranche) : ""; const showTrancheNotice = Boolean(activeTranche && shownTrancheKey === activeTrancheKey);
  useEffect(() => { if (!activeTranche || !activeTrancheKey || data.settings.seenWeeklyPlanTranches.includes(activeTrancheKey) || shownTrancheKey === activeTrancheKey) return; setShownTrancheKey(activeTrancheKey); window.dispatchEvent(new CustomEvent("buget-familie:local-settings", { detail: { seenWeeklyPlanTranches: [...data.settings.seenWeeklyPlanTranches, activeTrancheKey].slice(-80) } })); }, [activeTranche, activeTrancheKey, data.settings.seenWeeklyPlanTranches, shownTrancheKey]);
  const openSignal = (action: AdvisorAction) => onGo(action === "plan" ? "plan" : action === "objectives" ? "obligations" : action === "journal" ? "journal" : "obligations");
  return <div className="bf-page bf-today-workspace"><section className={`bf-today-situation ${overPlan ? "risk" : ""} ${!showTrancheNotice && !activeEnvelopeAlert ? "paired" : ""}`}><div className="bf-today-situation-top"><span className="bf-status-chip"><i /> {overPlan ? "Plan de revizuit" : "Ritm urmărit"}</span><time dateTime={isoToday()}>{dateText(isoToday(), true)}</time></div><div className="bf-today-situation-number"><p>{overPlan ? "Peste limita planului" : "Bani nerepartizați"}</p><strong>{money(Math.abs(math.remaining))}</strong><span>{overPlan ? "de acoperit prin limită, plicuri sau cheltuieli flexibile" : math.plan.nextPayday ? `${math.days} zile rămase · ritm prudent ${money(daily)}/zi` : "setează venitul următor pentru a calcula ritmul"}</span><HealthScoreBadge data={data} /></div><div className="bf-today-situation-actions"><button className="bf-today-add" onClick={onAdd}><Plus size={20} /> Înregistrează mișcare</button><button className="bf-today-plan-link" onClick={() => onGo("plan")}>Deschide planul <ChevronRight size={16} /></button></div></section></div>;
}
