import { useEffect, useMemo, useState } from "react";
import { Bot, ChevronDown, CircleCheck, Lightbulb, PieChart, Plus, Send, Sparkles, WalletCards, X } from "lucide-react";
import { expenseCategories, parseNaturalSpendScenario, type AppData, type Transaction } from "@/lib/finance-data";
import type { MainView } from "@/pages/home-kit";
import "../ai-companion.css";

export type NaturalDraft = Pick<Transaction, "amount" | "category" | "title" | "kind"> & { date?: string; note?: string };
type Props = { data: AppData; view: MainView; onAdd: () => void; onGo: (view: MainView) => void; onNaturalEntry: (draft: NaturalDraft) => void };
type ChatMessage = { id: string; role: "assistant" | "user"; text: string; action?: { label: string; type: "add" | "plan" | "journal" | "insights" } };
const CHAT_KEY = "buget-familie:ai-chat-v1";
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: number) => `${Math.round(value).toLocaleString("ro-RO")} RON`;
const naturalTitle = (raw: string, category?: string) => /combustibil|benzina|motorina/i.test(raw.normalize("NFD").replace(/[\u0300-\u036f]/g, "")) ? "Combustibil" : category || "Cheltuială";

export function AICompanion({ data, view, onAdd, onGo, onNaturalEntry }: Props) {
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [typing, setTyping] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>(() => { try { return JSON.parse(window.localStorage.getItem(CHAT_KEY) || "[]") as ChatMessage[]; } catch { return []; } });
  const monthSummary = useMemo(() => { const month = today().slice(0, 7); const current = data.transactions.filter((item) => item.date.startsWith(month)); return { income: current.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.amount, 0), expense: current.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0) }; }, [data]);
  const contextReply = useMemo(() => { if (!data.transactions.length) return "Sunt aici cu tine. Putem începe foarte simplu: îmi spui ce venituri ai, ce datorii există și pentru ce vrei să pui bani deoparte. Eu te ajut să le așezăm în aplicație."; if (!data.settings.salaryPlan.allocations.length) return "Văd că ai început să notezi mișcări, dar încă nu ai repartizări. Te pot ajuta să punem banii în plicuri pentru mâncare, facturi, transport și economii."; if (monthSummary.income > 0 && monthSummary.expense > monthSummary.income) return `M-am uitat la luna aceasta: ai ${money(monthSummary.expense)} cheltuieli și ${money(monthSummary.income)} venituri. Nu te judec — hai să vedem împreună ce ajustăm.`; return `Sunt cu tine în ${view === "today" ? "tabloul de azi" : "secțiunea deschisă"}. Dacă apare o cheltuială sau un venit, scrie-mi natural și îl pregătesc pentru tine.`; }, [data, monthSummary, view]);

  useEffect(() => { if (!open || messages.length) return; setMessages([{ id: "welcome", role: "assistant", text: contextReply }]); }, [open, messages.length, contextReply]);
  useEffect(() => { try { window.localStorage.setItem(CHAT_KEY, JSON.stringify(messages.slice(-30))); } catch { /* spațiu local indisponibil */ } }, [messages]);

  const addMessage = (entry: Omit<ChatMessage, "id">) => setMessages((current) => [...current, { ...entry, id: `${Date.now()}-${current.length}` }].slice(-30));
  const runAction = (type: "add" | "plan" | "journal" | "insights", label: string) => { addMessage({ role: "user", text: label }); setTyping(true); window.setTimeout(() => { setTyping(false); addMessage({ role: "assistant", text: type === "add" ? "Deschid formularul. Completează ce mai lipsește și verifică înainte să salvezi." : type === "plan" ? "Deschid planul. Acolo așezăm veniturile pe destinații și ritmuri." : type === "journal" ? "Deschid jurnalul și ne uităm la mișcările care contează." : "Deschid analiza ca să vedem tiparele lunii.", action: { type, label: type === "add" ? "Deschide formularul" : type === "plan" ? "Vezi planul" : type === "journal" ? "Vezi jurnalul" : "Vezi analiza" } }); }, 260); };
  const handleAction = (type: "add" | "plan" | "journal" | "insights") => { if (type === "add") onAdd(); else onGo(type); setOpen(false); };
  const send = () => { const raw = message.trim(); if (!raw) return; setMessage(""); addMessage({ role: "user", text: raw }); const parsed = parseNaturalSpendScenario(raw, [...expenseCategories, ...data.settings.customCategories]); setTyping(true); window.setTimeout(() => { setTyping(false); if (!parsed.understood) { addMessage({ role: "assistant", text: "Vreau să te ajut, dar nu am găsit suma. Încearcă, de exemplu: «am cheltuit 50 de lei pe combustibil» sau «am plătit 120 lei la Lidl»." }); return; } addMessage({ role: "assistant", text: `Am înțeles: ${parsed.title}, ${money(parsed.amount)}, ${parsed.timing === "mâine" ? "mâine" : "astăzi"}. Îți deschid formularul cu aceste date precompletate; verificăm împreună înainte de salvare.`, action: { type: "add", label: "Deschide și verifică" } }); onNaturalEntry({ kind: "expense", amount: parsed.amount, category: parsed.category || "Alimente", title: naturalTitle(raw, parsed.category), date: parsed.timing === "mâine" ? new Date(Date.now() + 86400000).toISOString().slice(0, 10) : today(), note: raw }); }, 420); };

  return <><button type="button" className={`ai-companion-trigger ${open ? "is-open" : ""}`} aria-label={open ? "Închide ghidul AI" : "Deschide ghidul AI"} onClick={() => setOpen((value) => !value)}><span className="ai-trigger-pulse" /><Sparkles size={21} /><span>Ghidul tău</span>{open ? <ChevronDown size={14} /> : <span className="ai-live">ONLINE</span>}</button>{open && <aside className="ai-companion-panel ai-chat-panel" aria-label="Conversație cu ghidul tău AI"><header className="ai-companion-head"><div className="ai-avatar"><Bot size={18} /></div><div><p className="ai-eyebrow">GHIDUL TĂU · ONLINE</p><h2>Sunt aici cu tine</h2><span className="ai-status"><i /> Îți răspund din contextul bugetului tău</span></div><button type="button" className="ai-close" aria-label="Închide ghidul" onClick={() => setOpen(false)}><X size={17} /></button></header><div className="ai-chat-history" aria-live="polite">{messages.map((item) => <div className={`ai-chat-row ${item.role}`} key={item.id}><div className="ai-chat-bubble">{item.role === "assistant" && <Bot size={14} /> }<span>{item.text}</span></div>{item.action && <button type="button" className="ai-chat-action" onClick={() => handleAction(item.action!.type)}><CircleCheck size={14} /> {item.action.label}</button>}</div>)}{typing && <div className="ai-chat-row assistant"><div className="ai-chat-bubble ai-typing"><i /><i /><i /></div></div>}</div><div className="ai-chat-suggestions"><button type="button" onClick={() => runAction("add", "Vreau să adaug o mișcare")}>+ Adaugă o mișcare</button><button type="button" onClick={() => runAction("plan", "Ajută-mă cu repartizarea")}>Repartizare</button><button type="button" onClick={() => runAction("journal", "Vreau să văd luna")}>Situația mea</button></div><form className="ai-natural-form ai-chat-input" onSubmit={(event) => { event.preventDefault(); send(); }}><label htmlFor="ai-natural-message">Scrie-mi orice despre banii tăi</label><div><input id="ai-natural-message" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="ex. am cheltuit 50 de lei pe combustibil" /><button type="submit" aria-label="Trimite mesajul"><Send size={16} /></button></div><p><Lightbulb size={12} /> Îți explic, te ghidez și îți cer confirmarea înainte să salvez.</p></form><p className="ai-privacy"><WalletCards size={13} /> Conversația este păstrată local pe acest dispozitiv.</p></aside>}</>;
}

export default AICompanion;
