import { useMemo } from "react";
import { Check, Lightbulb, TrendingDown, TrendingUp } from "lucide-react";
import type { AppData, BudgetAllocation } from "@/lib/finance-data";

type Recommendation = { allocation: BudgetAllocation; spent: number; count: number; average: number; recommended: number; direction: "up" | "down"; reason: string };
const money = (value: number) => new Intl.NumberFormat("ro-RO", { style: "currency", currency: "RON", maximumFractionDigits: 0 }).format(Number.isFinite(value) ? value : 0);
const round10 = (value: number) => Math.max(0, Math.round(value / 10) * 10);
const dateKey = (date: Date) => date.toISOString().slice(0, 10);

export function AllocationRecommendationsPanel({ data, allocations, periodDays, onApply }: { data: AppData; allocations: BudgetAllocation[]; periodDays: number; onApply: (allocation: BudgetAllocation, amount: number) => void }) {
  const recommendations = useMemo<Recommendation[]>(() => { const end = new Date(); const start = new Date(end.getTime() - 89 * 24 * 60 * 60 * 1000); const startKey = dateKey(start); const expenses = data.transactions.filter((item) => item.kind === "expense" && item.date >= startKey); return allocations.map((allocation) => { const matches = expenses.filter((item) => (item.allocationId ? item.allocationId === allocation.id : item.category === allocation.category && (!allocation.sourceId || item.sourceId === allocation.sourceId))); const spent = matches.reduce((sum, item) => sum + Math.max(0, item.amount), 0); const average = spent / 3; const targetForPeriod = average * Math.max(1, periodDays / 30); const currentForPeriod = Math.max(0, allocation.amount); const shouldIncrease = matches.length >= 3 && targetForPeriod > currentForPeriod * 1.12; const shouldDecrease = matches.length >= 3 && targetForPeriod < currentForPeriod * 0.78; if (!shouldIncrease && !shouldDecrease) return null; const recommended = round10(shouldIncrease ? targetForPeriod * 1.08 : Math.max(targetForPeriod * 1.12, currentForPeriod * 0.88)); return { allocation, spent, count: matches.length, average, recommended, direction: shouldIncrease ? "up" : "down", reason: shouldIncrease ? `Consumul mediu este cu ${Math.round((targetForPeriod / currentForPeriod - 1) * 100)}% peste suma actuală.` : `Consumul mediu este cu ${Math.round((1 - targetForPeriod / currentForPeriod) * 100)}% sub suma actuală.` }; }).filter((item): item is Recommendation => Boolean(item)).sort((a, b) => Math.abs(b.recommended - b.allocation.amount) - Math.abs(a.recommended - a.allocation.amount)).slice(0, 5); }, [allocations, data.transactions, periodDays]);
  return <section className="bf-allocation-recommendations" aria-labelledby="allocation-recommendations-title"><div className="bf-section-heading"><div><p className="bf-kicker">SUGESTII DIN ISTORIC</p><h2 id="allocation-recommendations-title">Plicuri care pot respira mai bine</h2></div><Lightbulb size={19} /></div><p className="bf-recommendation-intro">Comparăm ultimele 90 de zile cu suma actuală. Ajustarea este moderată și rămâne doar o propunere până la confirmare.</p>{recommendations.length ? <div className="bf-recommendation-list">{recommendations.map((item) => <article key={item.allocation.id} className={item.direction}><span className="bf-recommendation-icon">{item.direction === "up" ? <TrendingUp size={16} /> : <TrendingDown size={16} />}</span><div><b>{item.allocation.label}</b><small>{item.count} mișcări · medie {money(item.average)} / lună</small><p>{item.reason} Suma sugerată pentru perioada curentă: <strong>{money(item.recommended)}</strong>.</p></div><button type="button" onClick={() => onApply(item.allocation, item.recommended)}><Check size={14} /> Aplică</button></article>)}</div> : <div className="bf-recommendation-empty"><Check size={18} /><p>Nu există încă un tipar suficient de stabil pentru a sugera o schimbare. Păstrăm planul calm și predictibil.</p></div>}<small className="bf-recommendation-note">Recomandările sunt orientative, folosesc doar cheltuieli înregistrate și nu includ venituri viitoare sau evenimente excepționale.</small></section>;
}
