/** Atelierul Financiar 2.0 — statistici automat pe anul curent, din registrul real. */
import { BarChart3, CalendarRange, TrendingDown, TrendingUp } from "lucide-react";
import { categoryColors, type AppData } from "@/lib/finance-data";

const money = (value: number) => new Intl.NumberFormat("ro-RO", { style: "currency", currency: "RON", maximumFractionDigits: 0 }).format(value);
const months = ["Ian", "Feb", "Mar", "Apr", "Mai", "Iun", "Iul", "Aug", "Sep", "Oct", "Noi", "Dec"];

export function ReportsPanel({ data }: { data: AppData }) {
  const year = new Date().getFullYear();
  const yearTransactions = data.transactions.filter((item) => item.date.startsWith(String(year)));
  const income = yearTransactions.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.amount, 0);
  const expense = yearTransactions.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0);
  const monthly = months.map((label, index) => { const prefix = `${year}-${String(index + 1).padStart(2, "0")}`; const entries = yearTransactions.filter((item) => item.date.startsWith(prefix)); return { label, income: entries.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.amount, 0), expense: entries.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0) }; });
  const maxMonthly = Math.max(1, ...monthly.flatMap((item) => [item.income, item.expense]));
  const categories = Object.entries(yearTransactions.filter((item) => item.kind === "expense").reduce<Record<string, number>>((all, item) => ({ ...all, [item.category]: (all[item.category] || 0) + item.amount }), {})).sort((a, b) => b[1] - a[1]);
  const maxCategory = Math.max(1, ...categories.map(([, value]) => value));
  return <div className="bf-reports"><section className="bf-reports-hero"><div><p className="bf-kicker">STATISTICA ANUALĂ · {year}</p><h2>O privire peste <em>ritmul familiei.</em></h2><p>Nu este o comparație abstractă: fiecare coloană și categorie vine din mișcările înregistrate.</p></div><BarChart3 size={30} /></section><div className="bf-report-metrics"><article><span className="income"><TrendingUp size={16} /></span><p>Venituri anuale</p><strong>{money(income)}</strong></article><article><span className="expense"><TrendingDown size={16} /></span><p>Cheltuieli anuale</p><strong>{money(expense)}</strong></article><article><span className="balance"><CalendarRange size={16} /></span><p>Diferență anuală</p><strong className={income - expense < 0 ? "negative" : ""}>{money(income - expense)}</strong></article></div><section className="bf-report-card"><div className="bf-section-heading"><div><p className="bf-kicker">LUNĂ CU LUNĂ</p><h2>Venituri și cheltuieli</h2></div></div><div className="bf-month-chart" aria-label={`Statistici lunare pentru ${year}`}>{monthly.map((item) => <article key={item.label}><div className="bf-chart-bars"><span title={`Venituri: ${money(item.income)}`} className="income" style={{ height: `${Math.max(3, item.income / maxMonthly * 100)}%` }} /><span title={`Cheltuieli: ${money(item.expense)}`} className="expense" style={{ height: `${Math.max(3, item.expense / maxMonthly * 100)}%` }} /></div><b>{item.label}</b></article>)}</div><div className="bf-chart-legend"><span><i className="income" /> Venituri</span><span><i className="expense" /> Cheltuieli</span></div></section><section className="bf-report-card"><div className="bf-section-heading"><div><p className="bf-kicker">UNDE AU MERS BANII</p><h2>Categorii în anul curent</h2></div></div>{categories.length ? <div className="bf-category-report">{categories.map(([name, value]) => <article key={name}><div><span>{name}</span><b>{money(value)}</b></div><div><i style={{ width: `${value / maxCategory * 100}%`, background: categoryColors[name] || "#73847b" }} /></div></article>)}</div> : <p className="bf-empty-inline">Introdu cheltuieli pentru a activa statistica anuală.</p>}</section></div>;
}
