/** Atelierul Financiar 2.0 — rapoarte anuale și bilanț total, calculate exclusiv din registrul real. */
import { useState } from "react";
import { BarChart3, CalendarRange, Download, Landmark, PiggyBank, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { categoryColors, financialBalance, type AppData } from "@/lib/finance-data";
import { downloadMonthlyBalancePdf } from "@/lib/monthly-balance-pdf";

const money = (value: number) => new Intl.NumberFormat("ro-RO", { style: "currency", currency: "RON", maximumFractionDigits: 0 }).format(value);
const months = ["Ian", "Feb", "Mar", "Apr", "Mai", "Iun", "Iul", "Aug", "Sep", "Oct", "Noi", "Dec"];

export function ReportsPanel({ data }: { data: AppData }) {
  const year = new Date().getFullYear(); const currentMonth = `${year}-${String(new Date().getMonth() + 1).padStart(2, "0")}`; const isCollaborative = data.settings.members.length > 1; const [scope, setScope] = useState("family"); const [pdfMonth, setPdfMonth] = useState(currentMonth); const [exporting, setExporting] = useState(false); const selectedMember = data.settings.members.find((member) => member.id === scope); const perspective = selectedMember?.name || (isCollaborative ? "Familie" : "Personal");
  const scopedTransactions = data.transactions.filter((item) => !selectedMember || item.memberId === selectedMember.id);
  const yearTransactions = scopedTransactions.filter((item) => item.date.startsWith(String(year)));
  const income = yearTransactions.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.amount, 0);
  const expense = yearTransactions.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0);
  const totalBalance = financialBalance(data, undefined, undefined, selectedMember?.id);
  const annualBalance = financialBalance(data, `${year}-01-01`, `${year}-12-31`, selectedMember?.id);
  const monthly = months.map((label, index) => {
    const prefix = `${year}-${String(index + 1).padStart(2, "0")}`;
    const entries = yearTransactions.filter((item) => item.date.startsWith(prefix));
    return { label, income: entries.filter((item) => item.kind === "income").reduce((sum, item) => sum + item.amount, 0), expense: entries.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0) };
  });
  const maxMonthly = Math.max(1, ...monthly.flatMap((item) => [item.income, item.expense]));
  const categories = Object.entries(yearTransactions.filter((item) => item.kind === "expense").reduce<Record<string, number>>((all, item) => ({ ...all, [item.category]: (all[item.category] || 0) + item.amount }), {})).sort((a, b) => b[1] - a[1]);
  const maxCategory = Math.max(1, ...categories.map(([, value]) => value));

  const exportPdf = async () => { setExporting(true); try { await downloadMonthlyBalancePdf(data, pdfMonth, selectedMember?.id); } finally { setExporting(false); } };
  return <div className="bf-reports">
    <section className="bf-reports-hero"><div><p className="bf-kicker">STATISTICA ANUALĂ · {year}</p><h2>O privire peste <em>{selectedMember ? `ritmul lui ${selectedMember.name}` : isCollaborative ? "ritmul familiei" : "ritmul tău"}.</em></h2><p>Fiecare coloană, categorie și sumă de bilanț vine din mișcările introduse și din obiectivele declarate.</p></div><BarChart3 size={30} /></section>
    <section className="bf-report-card bf-report-balance"><div className="bf-section-heading"><div><p className="bf-kicker">BILANȚ TOTAL {perspective.toUpperCase()}</p><h2>Ce rămâne, <em>după ce tragem linie.</em></h2></div><WalletCards size={20} /></div>{isCollaborative && <div className="bf-balance-scope bf-report-scope" role="group" aria-label="Perspectiva raportului"><button className={scope === "family" ? "active" : ""} onClick={() => setScope("family")}>Familie</button>{data.settings.members.map((member) => <button key={member.id} className={scope === member.id ? "active" : ""} onClick={() => setScope(member.id)}>{member.name}</button>)}</div>}<p className="bf-balance-scope-note">{selectedMember ? "Mișcările și sursele membrului selectat; obligațiile și economiile comune rămân incluse." : "Toate mișcările, sursele și obligațiile înregistrate de familie."}</p><div className="bf-report-export"><div><label htmlFor="monthly-balance-pdf">Luna raportului PDF</label><input id="monthly-balance-pdf" type="month" value={pdfMonth} onChange={(event) => setPdfMonth(event.target.value)} /></div><button className="bf-secondary" disabled={exporting} onClick={exportPdf}><Download size={16} /> {exporting ? "Generăm PDF-ul…" : "Descarcă bilanțul PDF"}</button></div><div className="bf-report-metrics"><article><span className="balance"><WalletCards size={16} /></span><p>Poziție lichidă netă</p><strong className={totalBalance.netLiquidPosition < 0 ? "negative" : ""}>{money(totalBalance.netLiquidPosition)}</strong><small>solduri {money(totalBalance.liquidFunds)} − datorii {money(totalBalance.debtRemaining)}</small></article><article><span className="expense"><Landmark size={16} /></span><p>Rate declarate / lună</p><strong>{money(totalBalance.monthlyRates)}</strong><small>devin cheltuieli numai când sunt înregistrate</small></article><article><span className="income"><PiggyBank size={16} /></span><p>Economii urmărite</p><strong>{money(totalBalance.savingsCurrent)}</strong><small>separat de solduri, pentru a evita dubla numărare</small></article></div><p className="bf-report-note">Fluxul din {year}: <b className={annualBalance.cashflow < 0 ? "negative" : ""}>{money(annualBalance.cashflow)}</b> — venituri {money(annualBalance.income)} minus cheltuieli {money(annualBalance.expense)}. Acesta este un rezumat al datelor introduse, nu un extras bancar sau o recomandare financiară.</p></section>
    <div className="bf-report-metrics"><article><span className="income"><TrendingUp size={16} /></span><p>Venituri anuale</p><strong>{money(income)}</strong></article><article><span className="expense"><TrendingDown size={16} /></span><p>Cheltuieli anuale</p><strong>{money(expense)}</strong></article><article><span className="balance"><CalendarRange size={16} /></span><p>Diferență anuală</p><strong className={income - expense < 0 ? "negative" : ""}>{money(income - expense)}</strong></article></div>
    <section className="bf-report-card"><div className="bf-section-heading"><div><p className="bf-kicker">LUNĂ CU LUNĂ</p><h2>Venituri și cheltuieli</h2></div></div><div className="bf-month-chart" aria-label={`Statistici lunare pentru ${year}`}>{monthly.map((item) => <article key={item.label}><div className="bf-chart-bars"><span title={`Venituri: ${money(item.income)}`} className="income" style={{ height: `${Math.max(3, item.income / maxMonthly * 100)}%` }} /><span title={`Cheltuieli: ${money(item.expense)}`} className="expense" style={{ height: `${Math.max(3, item.expense / maxMonthly * 100)}%` }} /></div><b>{item.label}</b></article>)}</div><div className="bf-chart-legend"><span><i className="income" /> Venituri</span><span><i className="expense" /> Cheltuieli</span></div></section>
    <section className="bf-report-card"><div className="bf-section-heading"><div><p className="bf-kicker">UNDE AU MERS BANII</p><h2>Categorii în anul curent</h2></div></div>{categories.length ? <div className="bf-category-report">{categories.map(([name, value]) => <article key={name}><div><span>{name}</span><b>{money(value)}</b></div><div><i style={{ width: `${value / maxCategory * 100}%`, background: categoryColors[name] || "#73847b" }} /></div></article>)}</div> : <p className="bf-empty-inline">Introdu cheltuieli pentru a activa statistica anuală.</p>}</section>
  </div>;
}
